// Generated by tool/sync_web_runtime_config.sh. Do not edit directly.
export const firebaseWebConfig = {
  "apiKey": "AIzaSyAuP4nShQ60Axflrnjvplsro5OD2YjYslM",
  "authDomain": "profit-lens-prod-2e417.firebaseapp.com",
  "projectId": "profit-lens-prod-2e417",
  "storageBucket": "profit-lens-prod-2e417.firebasestorage.app",
  "messagingSenderId": "117544150167",
  "appId": "1:117544150167:web:9a18d96b6b193da94f75d2"
} as const;
