export const offerExtractionPrompt = [
  "You are extracting delivery offer data from a screenshot.",
  "Return ONLY valid JSON with this schema:",
  "{",
  "  \"offer\": {",
  "    \"payoutEuro\": number,",
  "    \"distanceKm\": number,",
  "    \"pickupName\": string | null,",
  "    \"pickupAddress\": string | null,",
  "    \"dropoffName\": string | null,",
  "    \"dropoffAddress\": string | null",
  "  },",
  "  \"confidence\": number,",
  "  \"rawText\": string",
  "}",
  "Use dot as decimal separator.",
  "If a field is unknown or not visible, set it to null.",
  "Address heuristics (common Uber Eats/Deliveroo cards):",
  "- If you see a restaurant/store name followed by a single full address line, treat it as:",
  "  pickupName = restaurant/store name, dropoffAddress = that address, pickupAddress = null, dropoffName = null.",
  "- If two distinct address lines are visible, use the first as pickupAddress and the second as dropoffAddress.",
  "- If only a business name is visible with no address, set pickupName and keep addresses null.",
  "- If a customer name is explicitly shown near the drop-off, set dropoffName. Otherwise keep dropoffName null.",
  "Do not include markdown fences or any extra text outside the JSON.",
].join("\n");
