// Generated by tool/sync_web_runtime_config.sh. Do not edit directly.
export const billingDefines = {
  stripePriceTier9: "price_1SyVqkBiu8Do3eGGArSLX40q",
  stripePriceTier24: "price_1SyVquBiu8Do3eGGZkQ3P8Es",
  stripePriceTier34: "price_1SyVr5Biu8Do3eGGIfO5JbiW",
} as const;
