// Generated by tool/sync_web_runtime_config.sh. Do not edit directly.
export const installDefines = {
  androidAppDownloadUrl: "/downloads/profit-lens-android-release.apk?v=f16827c6ca610a10",
} as const;
