#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
QWIK_DIR="$ROOT_DIR/apps/qwik"
CONFIG_SRC="$ROOT_DIR/web/firebase-web-config.js"
QWIK_PUBLIC_CONFIG="$QWIK_DIR/public/firebase-web-config.js"
QWIK_TS_CONFIG="$QWIK_DIR/src/lib/config/firebase-web-config.ts"

if [[ ! -f "$CONFIG_SRC" ]]; then
  echo "Missing $CONFIG_SRC" >&2
  exit 1
fi

mkdir -p "$(dirname "$QWIK_PUBLIC_CONFIG")"
mkdir -p "$(dirname "$QWIK_TS_CONFIG")"
mkdir -p "$QWIK_DIR/public/i18n"

cp "$CONFIG_SRC" "$QWIK_PUBLIC_CONFIG"

node <<'NODE'
const fs = require('fs');
const path = require('path');

const root = process.cwd();
const configPath = path.join(root, 'web', 'firebase-web-config.js');
const qwikTsConfigPath = path.join(root, 'apps', 'qwik', 'src', 'lib', 'config', 'firebase-web-config.ts');

const configSource = fs.readFileSync(configPath, 'utf8');
const configMatch = configSource.match(/PROFIT_LENS_FIREBASE_CONFIG\s*=\s*(\{[\s\S]*?\});/);
if (!configMatch) {
  throw new Error('Unable to parse web/firebase-web-config.js');
}

const configObj = Function(`"use strict"; return (${configMatch[1]});`)();
const tsBody = [
  '// Generated by tool/sync_web_runtime_config.sh. Do not edit directly.',
  `export const firebaseWebConfig = ${JSON.stringify(configObj, null, 2)} as const;`,
  '',
].join('\n');
fs.writeFileSync(qwikTsConfigPath, tsBody, 'utf8');

const locales = ['en', 'fr', 'ar'];
for (const locale of locales) {
  const arbPath = path.join(root, 'lib', 'l10n', `app_${locale}.arb`);
  const outPath = path.join(root, 'apps', 'qwik', 'public', 'i18n', `${locale}.json`);
  const arbRaw = fs.readFileSync(arbPath, 'utf8');
  const arb = JSON.parse(arbRaw);
  const dictionary = {};
  for (const [key, value] of Object.entries(arb)) {
    if (key.startsWith('@')) {
      continue;
    }
    if (typeof value === 'string') {
      dictionary[key] = value;
    }
  }
  fs.writeFileSync(outPath, `${JSON.stringify(dictionary, null, 2)}\n`, 'utf8');
}
NODE

echo "Synced Firebase web config + Qwik i18n dictionaries."
