#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
QWIK_DIR="$ROOT_DIR/apps/qwik"
ADMIN_DIR="$ROOT_DIR/apps/admin"
CONFIG_SRC="$QWIK_DIR/public/firebase-web-config.js"
QWIK_TS_CONFIG="$QWIK_DIR/src/lib/config/firebase-web-config.ts"
ADMIN_TS_CONFIG="$ADMIN_DIR/src/lib/config/firebase-web-config.ts"
ADMIN_PUBLIC_CONFIG="$ADMIN_DIR/public/firebase-web-config.js"
DEFINES_FILE="${DEFINES_FILE:-$ROOT_DIR/tool/dev_runtime_defines.json}"

if [[ ! -f "$CONFIG_SRC" ]]; then
  echo "Missing $CONFIG_SRC" >&2
  exit 1
fi

mkdir -p "$(dirname "$QWIK_TS_CONFIG")"
mkdir -p "$(dirname "$ADMIN_TS_CONFIG")"
mkdir -p "$(dirname "$ADMIN_PUBLIC_CONFIG")"

node <<'NODE'
const fs = require('fs');
const path = require('path');

const root = process.cwd();
const configPath = path.join(root, 'apps', 'qwik', 'public', 'firebase-web-config.js');
const qwikTsConfigPath = path.join(root, 'apps', 'qwik', 'src', 'lib', 'config', 'firebase-web-config.ts');
const adminTsConfigPath = path.join(root, 'apps', 'admin', 'src', 'lib', 'config', 'firebase-web-config.ts');
const adminPublicConfigPath = path.join(root, 'apps', 'admin', 'public', 'firebase-web-config.js');
const qwikBillingConfigPath = path.join(root, 'apps', 'qwik', 'src', 'lib', 'config', 'billing-defines.ts');
const definesPath = process.env.DEFINES_FILE || path.join(root, 'tool', 'dev_runtime_defines.json');

const configSource = fs.readFileSync(configPath, 'utf8');
const configMatch = configSource.match(/PROFIT_LENS_FIREBASE_CONFIG\s*=\s*(\{[\s\S]*?\});/);
if (!configMatch) {
  throw new Error('Unable to parse apps/qwik/public/firebase-web-config.js');
}

const configObj = Function(`"use strict"; return (${configMatch[1]});`)();
const tsBody = [
  '// Generated by tool/sync_web_runtime_config.sh. Do not edit directly.',
  `export const firebaseWebConfig = ${JSON.stringify(configObj, null, 2)} as const;`,
  '',
].join('\n');
fs.writeFileSync(qwikTsConfigPath, tsBody, 'utf8');
fs.writeFileSync(adminTsConfigPath, tsBody, 'utf8');
fs.writeFileSync(adminPublicConfigPath, configSource, 'utf8');

if (!fs.existsSync(definesPath)) {
  throw new Error(`Missing ${definesPath}`);
}
const defines = JSON.parse(fs.readFileSync(definesPath, 'utf8'));
const billingBody = [
  '// Generated by tool/sync_web_runtime_config.sh. Do not edit directly.',
  'export const billingDefines = {',
  `  stripePriceTier9: ${JSON.stringify(defines.STRIPE_PRICE_TIER_9 ?? '')},`,
  `  stripePriceTier24: ${JSON.stringify(defines.STRIPE_PRICE_TIER_24 ?? '')},`,
  `  stripePriceTier34: ${JSON.stringify(defines.STRIPE_PRICE_TIER_34 ?? '')},`,
  '} as const;',
  '',
].join('\n');
fs.writeFileSync(qwikBillingConfigPath, billingBody, 'utf8');
NODE

echo "Synced Firebase runtime config for Qwik + admin and billing defines for Qwik."
