export const bulkOfferExtractionPrompt = [
  "You extract delivery rows from one app screenshot.",
  "Return ONLY valid JSON.",
  "If a value is missing, set it to null.",
  "distanceKm must be numeric kilometers.",
  "durationMinutes must be numeric minutes.",
  "deliveryTime must use HH:mm 24h format when visible.",
  "Use dot decimal separators in JSON numbers.",
  "Schema:",
  "{",
  '  "providerHint": string | null,',
  '  "rawText": string,',
  '  "offers": [',
  "    {",
  '      "payoutEuro": number | null,',
  '      "distanceKm": number | null,',
  '      "durationMinutes": number | null,',
  '      "deliveryTime": string | null,',
  '      "pickupName": string | null,',
  '      "pickupAddress": string | null,',
  '      "dropoffName": string | null,',
  '      "dropoffAddress": string | null,',
  '      "tipEuro": number | null,',
  '      "confidence": number | null',
  "    }",
  "  ]",
  "}",
].join("\n");

export const bulkOfferExtractionSchema = {
  type: "object",
  properties: {
    providerHint: { type: ["string", "null"] },
    rawText: { type: "string" },
    offers: {
      type: "array",
      items: {
        type: "object",
        properties: {
          payoutEuro: { type: ["number", "null"] },
          distanceKm: { type: ["number", "null"] },
          durationMinutes: { type: ["number", "null"] },
          deliveryTime: { type: ["string", "null"] },
          pickupName: { type: ["string", "null"] },
          pickupAddress: { type: ["string", "null"] },
          dropoffName: { type: ["string", "null"] },
          dropoffAddress: { type: ["string", "null"] },
          tipEuro: { type: ["number", "null"] },
          confidence: { type: ["number", "null"] },
        },
        required: [
          "payoutEuro",
          "distanceKm",
          "durationMinutes",
          "deliveryTime",
          "pickupName",
          "pickupAddress",
          "dropoffName",
          "dropoffAddress",
          "tipEuro",
          "confidence",
        ],
        additionalProperties: false,
      },
    },
  },
  required: ["providerHint", "rawText", "offers"],
  additionalProperties: false,
} as const;
